bookstore/urls.py
from django.urls import path
from .views import *

app_name = 'bookstore'

urlpatterns = [
    path('books/', book_list, name='book-list'),
    path('books/<int:pk>/', book_detail, name='book-detail'),
    path('authors/', author_list, name='author-list'),
    path('authors/<int:pk>', author_detail, name='author-detail'),
    path('authors/<int:pk>/books', books_by_author, name='books-by-author')
]

django_week_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookstore/', include('bookstore.urls')),
    path('', include('firstapp.urls')),

]

firstapp/urls.py
from django.urls import path
from .views import *

app_name = 'firstapp'

urlpatterns = [
    path('', hellodjango),
    path('date/', handler_date),
    path('date/<str:date>', handler_date1),
    path('<str:name>/', handler_name),

]

bookstore/models.py
from django.db import models

# Create your models here.

bookstore/views.py
from django.http import HttpResponse
from django.shortcuts import render

books = [
    {
        'id': 1,
        'title': 'Python Crash Course',
        'released_year': 2016,
        'description': 'It does what it says on the tin, and it does it really well. The book starts out with a '
                       'walkthrough of the basic Python elements and data structures, working through variables, '
                       'strings, numbers, lists, and tuples, outlining how you work with each of them. Next, '
                       'if statements and logical tests are covered, followed by a dive into dictionaries. After '
                       'that, the book covers user input, while loops, functions, classes, and file handling, '
                       'as well as code testing and debugging. That’s just the first half of the book! In the second '
                       'half, you work on three major projects, creating some clever, fun applications. The first '
                       'project is an Alien Invasion game, essentially Space Invaders, developed using the pygame '
                       'package. You design a ship (using classes), then program how to pilot it and make it fire '
                       'bullets. Then, you design several classes of aliens, make the alien fleet move, and make it '
                       'possible to shoot them down. Finally, you add a scoreboard and a list of high scores to '
                       'complete the game. After that, the next project covers data visualization with matplotlib, '
                       'random walks, rolling dice, and a little bit of statistical analysis, creating graphs and '
                       'charts with the pygal package. You learn how to download data in a variety of formats, '
                       'import it into Python, and visualize the results, as well as how to interact with web APIs, '
                       'retrieving and visualizing data from GitHub and HackerNews. The third project walks you '
                       'through the creation of a complete web application using Django to set up a Learning Log to '
                       'track what users have been studying. It covers how to install Django, set up a project, '
                       'design your models, create an admin interface, set up user accounts, manage access controls '
                       'on a per-user basis, style your entire app with Bootstrap, and then finally deploy it to '
                       'Heroku. This book is well written and nicely organized. It presents a large number of useful '
                       'exercises as well as three challenging and entertaining projects that make up the second half '
                       'of the book. (Reviewed by David Schlesinger.)',
        'author_id': 1,
    },
    {
        'id': 2,
        'title': 'Head-First Python, 2nd edition',
        'released_year': 2016,
        'description': 'I really like the Head-First series of books, although they’re admittedly lighter weight in '
                       'overall content than many of the other recommendations in this section. The trade-off is the '
                       'that this approach makes the book more user-friendly. If you’re the kind of person who likes '
                       'to learn things one small, fairly self-contained chunk at a time, and you want to have lots '
                       'of concrete examples and illustrations of the concepts involved, then the Head-First series '
                       'is for you. The publisher’s website has the following to say about their approach: “Based on '
                       'the latest research in cognitive science and learning theory, Head-First Python uses a '
                       'visually rich format to engage your mind, rather than a text-heavy approach that puts you to '
                       'sleep. Why waste your time struggling with new concepts? This multi-sensory learning '
                       'experience is designed for the way your brain really works.” (Source) Chock full of '
                       'illustrations, examples, asides, and other tidbits, Head-First Python is consistently '
                       'engaging and easy to read. This book starts its tour of Python by diving into lists and '
                       'explaining how to use and manipulate them. It then goes into modules, errors, '
                       'and file handling. Each topic is organized around a unifying project: building a dynamic '
                       'website for a school athletic coach using Python through a Common Gateway Interface (CGI). '
                       'After that, the book spends time teaching you how to use an Android application to interact '
                       'with the website you created. You learn to handle user input, wrangle data, and look into '
                       'what’s involved in deploying and scaling a Python application on the web. While this book '
                       'isn’t as comprehensive as some of the others, it covers a good range of Python tasks in a way '
                       'that’s arguably more accessible, painless, and effective. This is especially true if you find '
                       'the subject of writing programs somewhat intimidating at first. This book is designed to '
                       'guide you through any challenge. While the content is more focused, this book has plenty of '
                       'material to keep you busy and learning. You will not be bored. If you find most programming '
                       'books to be too dry, this could be an excellent book for you to get started in Python. ('
                       'Reviewed by David Schlesinger and Steven C. Howell.)',
        'author_id': 2,
    },
    {
        'id': 3,
        'title': 'Invent Your Own Computer Games with Python, 4th edition',
        'released_year': 2017,
        'description': 'If games are your thing, or you even have a game idea of your own, this would be the perfect '
                       'book to learn Python. In this book, you learn the fundamentals of programming and Python with '
                       'the application exercises focused on building classic games. Starting with an introduction to '
                       'the Python shell and the REPL loop, followed by a basic “Hello, World!” script, '
                       'you dive right into making a basic number-guessing game, covering random numbers, '
                       'flow control, type conversion, and Boolean data. After that, a small joke-telling script is '
                       'written to illustrate the use of print statements, escape characters, and basic string '
                       'operations. The next project is a text-based cave exploration game, Dragon’s Realm, '
                       'which introduces you to flowcharts and functions, guides you through how to define your own '
                       'arguments and parameters, and explains Boolean operators, global and local scope, '
                       'and the sleep() function. After a brief detour into how to debug your Python code, '
                       'you next implement the game of Hangman, using ASCII artwork, while learning about lists, '
                       'the in operator, methods, elif statements, the random module, and a handful of string '
                       'methods. You then extend the Hangman game with new features, like word lists and difficulty '
                       'levels, while learning about dictionaries, key-value pairs, and assignment to multiple '
                       'variables. Your next project is a Tic-Tac-Toe game, which introduces some high-level '
                       'artificial intelligence concepts, shows you how to short-circuit evaluation in conditionals, '
                       'and explains the None value as well as some different ways of accessing lists. Your journey '
                       'through the rest of the book proceeds in a similar vein. You’ll learn nested loops while '
                       'building a Mastermind-style number guessing game, Cartesian coordinates for a Sonar Hunt '
                       'game, cryptography to write a Caesar cipher, and artificial intelligence when implementing '
                       'Reversi (also known as Othello), in which the computer can play against itself. After all of '
                       'this, there’s a dive into using graphics for your games with PyGame: you’ll cover how to '
                       'animate the graphics, manage collision detection, as well as use sounds, images, and sprites. '
                       'To bring all these concepts together, the book guides you through making a graphical '
                       'obstacle-dodging game. This book is well done, and the fact that each project is a '
                       'self-contained unit makes it appealing and accessible. If you’re someone who likes to learn '
                       'by doing, then you’ll enjoy this book. The fact that this book introduces concepts only as '
                       'needed can be a possible disadvantage. While it’s organized more as a guide than a reference, '
                       'the broad range of contents taught in the context of familiar games makes this one of the '
                       'best books for learning Python. (Reviewed by David Schlesinger.)',
        'author_id': 3,
    },
    {
        'id': 4,
        'title': 'Think Python: How to Think Like a Computer Scientist, 2nd edition',
        'released_year': 2015,
        'description': 'If learning Python by creating video games is too frivolous for you, consider Allen Downey’s '
                       'book Think Python, which takes a much more serious approach. As the title says, the goal of '

bookstore/templates/bookstore/author_books.html
{% extends 'base.html' %}

{% block title %}
    All books
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5 text-center">
            <h3>{{author.first_name|upper}} {{author.last_name|upper}}</h3>
        </div>
        <div class="row mt-5">
            {% for book in books %}
                <div class="col-6">
                    <div class="container p-5">
                        <div class="row text-center">
                            <h5>{{ book.title }}</h5>
                        </div>
                        <div class="row text-center p-3">
                            <p>{{ book.description|slice:":200"}}</p>
                        </div>
                        <div class="row justify-content-between">
                            <div class="col-6 text-center">
                                <h6> Book release year: {{ book.released_year }}</h6>
                            </div>
                            <div class="col-6 text-center">
                                <a href="{% url 'bookstore:book-detail' book.id %}" class="text-decoration-none"><h6 class="text-info"> More about this book </h6></a>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bookstore/templates/bookstore/author_detail.html
{% extends 'base.html' %}

{% block title %}
    {{author.first_name}} {{author.last_name}}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5 text-center">
            <h3>{{author.first_name|upper}} {{author.last_name|upper}}</h3>
        </div>
        <div class="row mt-5 text-center">
            <h6>
                {{author.first_name}} {{author.last_name}}, he is {{author.age}} year old now,
                and in his years he wrote many interesting books,
                <a href="{% url 'bookstore:books-by-author' author.id %}" class="text-decoration-none" class="text-info"> here are some of them.</a>
            </h6>
        </div>
    </div>
{% endblock %}

bookstore/templates/bookstore/author_list.html
{% extends 'base.html' %}

{% block title %}
    All authors
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            {% for author in authors %}
                <div class="col-4">
                    <div class="container p-5">
                        <div class="row text-center">
                            <div class="col-6 text-center">
                                <h5>{{author.first_name}} {{author.last_name}}</h5>
                            </div>
                            <div class="col-6 text-center">
                                <a href="{% url 'bookstore:author-detail' author.id %}" class="text-decoration-none"><h6 class="text-info"> More about {{author.first_name}} </h6></a>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bookstore/templates/bookstore/book_detail.html
{% extends 'base.html' %}

{% block title %}
    {{book.title}}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5 text-center">
            <h2>{{book.title}}</h2>
        </div>

        <div class="row m-3 text-center">
            <h5>This book was written in {{book.released_year}} by {{author.first_name}} {{author.last_name}} </h5>
        </div>
        <div class="row text-center">
            <a href="{% url 'bookstore:author-detail' author.id %}" class="text-decoration-none"><h6 class="text-info"> More about {{author.first_name}} {{author.last_name}} </h6></a>
        </div>

        <div class="row p-5 text-center">
            <p>{{book.description}}</p>
        </div>
    </div>
{% endblock %}

bookstore/templates/bookstore/books_list.html
{% extends 'base.html' %}

{% block title %}
    All books
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            {% for book in books %}
                <div class="col-6">
                    <div class="container p-5">
                        <div class="row text-center">
                            <h5>{{ book.title }}</h5>
                        </div>
                        <div class="row text-center p-3">
                            <p>{{ book.description|slice:":200"}}</p>
                        </div>
                        <div class="row justify-content-between">
                            <div class="col-6 text-center">
                                <h6> Book release year: {{ book.released_year }}</h6>
                            </div>
                            <div class="col-6 text-center">
                                <a href="{% url 'bookstore:book-detail' book.id %}" class="text-decoration-none"><h6 class="text-info"> More about this book </h6></a>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}