bookstore/urls.py
from django.urls import path
from .views import *

app_name = 'bookstore'

urlpatterns = [
    path('books/', book_list, name='book-list'),
    path('books/<int:pk>/', book_detail, name='book-detail'),
    path('authors/', author_list, name='author-list'),
    path('authors/<int:pk>', author_detail, name='author-detail'),
    path('authors/<int:pk>/books', books_by_author, name='books-by-author')
]

django_week_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookstore/', include('bookstore.urls')),
    path('', include('firstapp.urls')),

]

firstapp/urls.py
from django.urls import path
from .views import *

app_name = 'firstapp'

urlpatterns = [
    path('', hellodjango),
    path('date/', handler_date),
    path('date/<str:date>', handler_date1),
    path('<str:name>/', handler_name),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'bookstore/img/fav.png' %}" type="image/png">
</head>
<body class="bg=light" >
    <div class="container" >
        <div class="row justify-content-evenly border-bottom mt-5">
            <div class="col-6">
                <a href="{% url 'bookstore:book-list' %}" class="text-decoration-none"><h4 class="text-center text-info">All books</h4></a>
            </div>
            <div class="col-6">
                <a href="{% url 'bookstore:author-list' %}" class="text-decoration-none"><h4 class="text-center ttext-info">All authors</h4></a>
            </div>
        </div>
    </div>

    {% block content %} {% endblock %}
</body>
</html>